project:
  type: website

website:
  title: "Jonathan Wilson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
  page-footer:
    center:
      - text: "© 2025 Jonathan Wilson"
      - icon: github
        aria-label: GitHub
        href: https://github.com/jonathanwilsonami/
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/jonathanwil/
      - icon: envelope
        aria-label: Email
        href: mailto:jonwilami@gmail.com

  site-url: https://jonathanwil.com

  # GA4 or Tracking ID
  google-analytics:
    tracking-id: "G-57REGYTJNR"
    storage: cookies
  
  # Cookie banner that controls GA4 loading
  cookie-consent:
    type: express
    policy-url: /privacy.html
    prefs-text: "Cookie settings"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
                





