project:
  type: website
  resources:
    - images/**
    - static/external/**

website:
  title: "Jonathan Wilson"
  favicon: images/about/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - text: About
            href: about.qmd
          - text: Books
            href: books.qmd
      - href: research/index.qmd 
        text: Research
      - text: Projects
        menu:
          - text: All Projects
            href: projects/index.qmd
          - text: Data Viz
            href: projects/data-viz/index.qmd
          - text: Intelligent Systems & Decision Modeling
            href: projects/ai-ml/index.qmd
          - text: Tech
            href: projects/tech/index.qmd
          - text: Construction
            href: projects/construction/index.qmd
      - text: Blog
        menu:
          - text: All Posts
            href: blog/index.qmd
          - text: Travel
            href: blog/travel.qmd
          - text: Tech
            href: blog/tech.qmd
  page-footer:
    center:
      - text: "© 2026 Jonathan Wilson"
      - icon: github
        aria-label: GitHub
        href: https://github.com/jonathanwilsonami/
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/jonathanwil/
      - icon: envelope
        aria-label: Email
        href: mailto:jonwilami@gmail.com

  site-url: https://jonathanwil.com

  # GA4 or Tracking ID
  google-analytics:
    tracking-id: "G-57REGYTJNR"
    storage: cookies
  
  # Cookie banner that controls GA4 loading
  cookie-consent:
    type: express
    policy-url: /privacy.html
    prefs-text: "Cookie settings"

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet"
                href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
                





